import AdminLayout from "@/components/layout/AdminLayout";
import Container from "@/components/shared/Container";
import Footer from "@/components/shared/footer/Footer";
import Header from "@/components/shared/header/Header";
import Loading from "@/components/shared/loading/Loading";
import Main from "@/components/shared/main/Main";
import Navbar from "@/components/shared/navbar/Navbar";
import {AuthProvider} from "@/utils/providers/AuthProvider";
import {Providers} from "@/utils/redux/Provider";
import {getServerSession} from "next-auth";
import Link from "next/link";
import {Suspense} from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AdminLayout>
      <Suspense fallback={<Loading />}>{children}</Suspense>
    </AdminLayout>
  );
}
