import { AuthProvider } from "@/utils/providers/AuthProvider";
import { Providers } from "@/utils/redux/Provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider session={session || undefined}>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
